### ISSUE TITLE
Broadlink Dooya

### ISSUE THREAD

**Issue by Maxmudjon** [nick7zmail/MajorDoMo-dev_broadlink#6]
Я могу управлять Dooya DT360E через MajorDoMo ?

**Comment by nick7zmail** [comment]
Привет. Пока нет, пытаемся разобраться с протоколом. В перспективе - добавим скорее всего.

_Sent from my Sony C6603 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Maxmudjon** [comment]
код на NodeJS будет ?

**Comment by nick7zmail** [comment]
Нет, на php. Модули в системе majordomo на php.

_Sent from my Sony C6603 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Maxmudjon** [comment]
Я хотел писать плагин для хомбриджа  по этому нужен nodejs код

**Comment by nick7zmail** [comment]
Ну никто ж не мешает переписать php код на nodejs.. 

_Sent from my Sony C6603 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Maxmudjon** [comment]
спасибо буду ждать удачи вам

**Comment by Maxmudjon** [comment]
А теперь можно управлять ?
и как объясните пожалуйста

**Comment by nick7zmail** [comment]
Пока нет...у меня сейчас крайне мало времени на модуль...тем более самого девайса у меня нет....был бы - давно бы, наверное, поддержка появилась...а на форуме пока не сильно активно пытаются добавить эту поддержку...

**Comment by Maxmudjon** [comment]
у меня он есть как я могу помочь

**Comment by nick7zmail** [comment]
http://majordomo.smartliving.ru/forum/viewtopic.php?p=56154#p56154
Примерно так...
(на страницах до этого - тоже инфа полезная)

**Comment by Maxmudjon** [comment]
Notice: Undefined index: mode in C:\_majordomo\htdocs\modules\dev_broadlink\broadlink_debug_scr.php on line 2

**Comment by nick7zmail** [comment]
да...ща его вызывать надо broadlink_debug_scr.php?mode=decrypt для расшифровки...либо mode=command (или что-то другое) для отправки каких-либо комманд...команда тоже в скрипте прописана, её можно менять..

**Comment by Maxmudjon** [comment]
http://localhost/modules/dev_broadlink/broadlink_debug_scr.php?mode=decrypt?ip=ip_устройства

**Comment by nick7zmail** [comment]
ну для decrypt ip необязателен....там нужно пакет запихнуть в переменную $wireshark, и код и айди устройства из базы вытащить, как прописано во второй ссылке 4 сообщения назад.

**Comment by Maxmudjon** [comment]
![final_bstsnapshot_777751](https://user-images.githubusercontent.com/23142922/29367013-fc959666-82b4-11e7-9b1d-85481a1081bd.jpg)

**Comment by nick7zmail** [comment]
поле publicKey открой...там должны быть цифры-буквы...это ключ, который надо забить в скрипт вместа с TerminalID

**Comment by Maxmudjon** [comment]
он не открывается

**Comment by nick7zmail** [comment]
ссылка для расшифровки точно открывается
http://ip/modules/dev_broadlink/broadlink_debug_scr.php?mode=decrypt
для выполнения команд - да, не работает, надо несколько функций удалить, повторяющихся в broadlink.class.php.

**Comment by Maxmudjon** [comment]
http://ip/modules/dev_broadlink/broadlink_debug_scr.php?mode=decrypt

что должен показывает ?

Я кое что уточнил, на каждом  пакеты есть МАС адрес толка обратном порядке 
5aa5aa555aa5aa550000000000000000000000000000000000000000000000000dd000004d4e6a00a08147f9ff34ea3401000000b7c00000096431955a16fe74b0c83e3ccf190242
                                                                                34:ea:34:ff:f9:47

**Comment by Maxmudjon** [comment]
http://majordomo.smartliving.ru/forum/viewtopic.php?p=55999#p55999

Я оттуда скачал broadlink.php и изменил 
//смартфон
$key_authorized = array(0x38, 0x1d, 0x66, 0x3d, 0x38, 0x1d, 0x66, 0x3d, 0x6e, 0x90, 0xdc, 0x2c, 0xa5, 0x03, 0x53, 0x1c);
$id_authorized = array(1, 0, 0, 0);
эти мои 
![image](https://user-images.githubusercontent.com/23142922/29499139-d999ccd2-8623-11e7-8b08-48886c5e1567.png)

![111111111](https://user-images.githubusercontent.com/23142922/29499201-458ad43a-8625-11e7-8214-9ca86185fa7c.png)

**Comment by Maxmudjon** [comment]
теперь как отправит код или пайлоад ?

**Comment by eschava** [comment]
https://github.com/mjg59/python-broadlink/pull/134
в python-broadlink появилась поддержка dooya

**Comment by nick7zmail** [comment]
Ещё бы на php кто нить её переписал бы...

**Comment by nick7zmail** [comment]
Поддержка добавлена, тема, думаю, закрыта =)
